import {StyleSheet} from 'react-native';
import {appColors} from '../../../../../../theme/appColors';
import {appSizes} from '../../../../../../theme/appSizes';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  logoContainer: {
    flexBasis: 'auto',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal:20,
    // alignItems: '',
    marginVertical: appSizes.x,
    marginBottom: appSizes.height * 0.07,
  },
  bottomSection: {
    backgroundColor: appColors.white,
    flex: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: 'relative',
    zIndex: 10,
    height: '100%',
    paddingHorizontal: appSizes.padding_x,
    // marginTop:-15
  },
  circles: {
    position: 'absolute',
    top: 5,
    marginTop: 10,
    width: appSizes.width,
    alignItems: 'center',
    zIndex: -1,
  },
  blueCircle: {
    position: 'absolute',
    top: -15,
    width: appSizes.width,
    alignItems: 'center',
  },
  socialBtnContainer: {
    width: '98%',
    height: 60,
    marginBottom: 20,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: appColors.dark,
    borderWidth: 0.8,
    flexDirection: 'row',
    columnGap: 10,
    alignSelf: 'center',
  },
  textSocail: {
    fontSize: appSizes.font_l,
    color: appColors.black,
    fontWeight: '500',
    fontFamily: 'Noto Sans',
  },
  orContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginBottom: appSizes.spacing_m,
  },
  orText: {
    color: '#B9B9B9',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Noto Sans',
  },
  line: {
    width: 51,
    height: 1,
    backgroundColor: '#B9B9B9',
    fontFamily: 'Noto Sans',
  },
  btn: {
    backgroundColor: appColors.primary,
    // borderColor: appColors.primary,
    // borderWidth: 0.8,
    marginBottom: 12,
  },
  loginTextContainer: {
    marginTop: appSizes.spacing_xxxx,
    flexDirection: 'row',
    flexBasis: 'auto',
    justifyContent: 'space-between',
    marginBottom: appSizes.spacing_m,
  },
  loginText: {
    color: appColors.textColor,
    fontSize: 22,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'Noto Sans',
  },
  loginTextSub: {
    color: appColors.textColor,
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '400',
    width: appSizes.width * 0.7,
    lineHeight: 20,
    marginTop: 5,
    fontFamily: 'Noto Sans',
  },
  yellowIcon: {
    // marginTop: 5,
  },
  textArea: {
    borderRadius: 16,
    borderColor: '#1D5EDD',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    marginBottom: 40,
    marginTop: 10,
  },
  skipContainer: {
    // paddingHorizontal: 20,
    // paddingVertical: 8,
    backgroundColor: appColors.primary,
    borderRadius: appSizes.radius_m,
    width: 81,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  skipText: {
    color: appColors.white,
    fontSize: 16,
    fontFamily: 'Noto Sans',
  },
  rowAgree: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    columnGap: 6,
    width: '94%',
    marginBottom: appSizes.spacing_l,
    // marginLeft: 10,
    // marginTop:appSizes.spacing_s
  },
  Circle: {
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
    backgroundColor: appColors.secondary,
    borderWidth: 1,
    borderColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop:2,
  },
  innerCircle: {
    width: 13,
    height: 13,
    borderRadius: 13,
    backgroundColor: appColors.primary,
  },
  agree: {
    color: appColors.black,
    fontSize: appSizes.font_m - 1,
    fontWeight: '400',
    textAlign: 'left',
    fontFamily: 'Noto Sans',
  },
  agreeLine: {
    color: appColors.primary,
    textDecorationLine: 'underline',
    fontFamily: 'Noto Sans',
  },
  Image: {
    height: 30,
    width: 30,
  },
  InputStyle: {
    borderRadius: 16,
    borderColor: '#1D5EDD',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 4,
    // borderBottomWidth: 0.5,
    height: 50,
    width: '49%',
  },
  labelStyle: {
    color: '#000',
    fontSize: 18,
    fontWeight: '400',
    marginBottom: 10,
    marginLeft: 2,
    fontFamily: 'Noto Sans',
  },
  InputStyleWithOutWidth: {
    borderRadius: 16,
    borderColor: '#1D5EDD',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 4,
    // borderBottomWidth: 0.5,
    height: 50,
  },
  labelStyle1: {
    fontSize: 18,
    fontWeight: '500',
    color: '#000',
    marginLeft: 8,
    marginBottom: 5,
    fontFamily: 'Noto Sans',
  },
  dateStyle:{
    borderRadius: 16,
    borderColor: '#1D5EDD',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 4,
    // borderBottomWidth: 0.5,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  rectangleText: {
    color: appColors.primary,
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 10,
    fontFamily:'Noto Sans'  
  },
  rectangleText1: {
    color: appColors.primary,
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: -7,
    fontFamily:'Noto Sans',
    marginBottom:10
  },
  ModalHeaderContanier: {
    width: '100%',
    alignItems: "center",
    paddingHorizontal: appSizes.padding_m,
    
  },
  ModalContanier: {
    width: '100%',
    // alignItems: "center",
    paddingHorizontal: appSizes.padding_m,
    marginTop: 2
  },
  questionText:{
    color: appColors.dark,
    fontSize: 16,
    fontWeight: '400',
    textAlign: 'left',
    marginTop: 10,
    alignSelf:"flex-start",
    fontFamily:'Noto Sans'
  },
});

export default styles;
